### ISSUE TITLE
Keyerror : resnet_v1_50/block3/unit_12/bottleneck_v1'

### ISSUE THREAD

**Issue by prashantsingh905** [eldar/pose-tensorflow#1]
I am trying to train the network resnet_v1_50 ..but i am getting this error with resnet_50 .  I am not facing any issues with resnet_101.

Here is the config file i am using:

```
dataset: /notebooks/posetensorflow/dataset/cropped/dataset.mat
dataset_type: "mpii"

pos_dist_thresh: 17
global_scale: 0.8452830189
scale_jitter_lo: 0.85
scale_jitter_up: 1.15

net_type: resnet_50
init_weights: ../../pretrained/resnet_v1_50.ckpt

location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801

intermediate_supervision: true
intermediate_supervision_layer: 12

max_input_size: 850
multi_step:
- [0.005, 10000]
- [0.02, 430000]
- [0.002, 730000]
- [0.001, 1030000]
display_iters: 5
save_iters: 60

mirror: true
```

`Traceback (most recent call last):
  File "../../../train.py", line 145, in <module>
    train()
  File "../../../train.py", line 90, in train
    losses = pose_net(cfg).train(batch)
  File "/notebooks/posetensorflow/nnet/pose_net.py", line 93, in train
    heads = self.get_net(batch[Batch.inputs])
  File "/notebooks/posetensorflow/nnet/pose_net.py", line 83, in get_net
    return self.prediction_layers(net, end_points)
  File "/notebooks/posetensorflow/nnet/pose_net.py", line 72, in prediction_layers
    block_interm_out = end_points[interm_name]                
KeyError: 'resnet_v1_50/block3/unit_12/bottleneck_v1'`

**Comment by eldar** [comment]
Hey,

Can you try and remove the lines

```
intermediate_supervision: true
intermediate_supervision_layer: 12
```

This is intermediate supervision setting that was designed for ResNet-101.
Alternatively you can set `intermediate_supervision_layer` to `1`, for example.
This places a loss at layer in the fourth bank (block3) of ResNet, and for a 50-layer
version there's only 3 of them. For ResNet-50 it is not necessary to use intermediate
supervision but you can try both with and without and see what works best for you. 

Cheers,
Eldar.

**Comment by eldar** [comment]
Closing as this is no longer an issue.
