### ISSUE TITLE
python_tf: command not found compile.sh

### ISSUE THREAD

**Issue by fazilaltinel** [eldar/pose-tensorflow#13]
According to your instructions, in order to run multiple people demo code, I need to run `$ ./compile.sh` command. When I run the command, I get the following error message: 

`python_tf: not found`

I searched on Google for `python_tf`. I couldn't find any package named python_tf. Is this an alias that you use in your system? If so, could you please share it?

Fazil

**Comment by eldar** [comment]
Hi, sorry, my own alias for python slipped in the repository. I will fix it soon, but in the meantime you can just correct it to python, assuming that you are running it within corresponding virtualenv.

**Comment by fazilaltinel** [comment]
Thank you for your prompt reply.

I will change `python_tf setup.py build_ext --inplace` lines to `python setup.py build_ext --inplace`.

Fazil

**Comment by eldar** [comment]
The fix pushed now.
