### ISSUE TITLE
trying to run demo nnet predict not found

### ISSUE THREAD

**Issue by trops** [eldar/pose-tensorflow#16]
Maybe Im missing something simple but im trying to run the demo, I downloaded all the mpii files and running python demo/singleperson.py results in 

```
File "demo/singleperson.py", line 9, in <module>
    from nnet import predict
ImportError: No module named nnet
```

I must be doing something wrong here.

**Comment by trops** [comment]
its late. I think I misread the docs...python 3 here I come. ;-)

**Comment by lisayan** [comment]
How did you fix it? I have a similar issue running the multi-person demo
