### ISSUE TITLE
nms_grid.c:437:18: fatal error: vector : No such file or directory

### ISSUE THREAD

**Issue by a2940519** [eldar/pose-tensorflow#20]
Hi , I've tried  demo_multiperson.py , but failed to run. 

npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \

nms_grid.c:437:18: fatal error: vector

ImportError: Building module nms_grid failed: ["CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n"]

I tried a lot of methods, but I still can't solve it. What should I do?

Thanks!

**Comment by eldar** [comment]
Hi,

This code has parts written in C++ and we use Cython to compile wrappers so it can be used in Python. When you run Cython, you appear to be generating plain C files `nms_grid.c` and not C++ (would have been `nms_grid.cpp`). For me it does generate nms_grid.cpp, and I also checked the Cython documentation again - the code contains all required features for the compiler to recognise to compile it into C++ code.

**Comment by eldar** [comment]
Can you please look at the contents off `lib/nms_cython` directory and check whether it generated C++ or C code. Also, are you using python3? `compile.sh` script actually calls `python` assuming you are in a `virtualenv` with version 3 as default. If not, then it will be calling python 2. If not, try to modify `compile.sh` to `python3`.

**Comment by a2940519** [comment]
Thank you for your help. @eldar 
 According to your method, the problem has been successfully solved.
