### ISSUE TITLE
Art-track

### ISSUE THREAD

**Issue by bhack** [eldar/pose-tensorflow#22]
I see in the readme that you are referencing art-track but the [dataset link seems unaviable](http://pose.mpi-inf.mpg.de/art-track/). Is the tracking component and the dataset released?

**Comment by bhack** [comment]
I suppose that dataset will be released with the code in https://github.com/eldar/pose-tensorflow/issues/19 right?

**Comment by eldar** [comment]
Hi,

We will be actually releasing an extended version of this dataset at https://posetrack.net/ You can already download a sizeable teaser of the data.

Cheers,
Eldar.

**Comment by bhack** [comment]
Oh it will be part of the ICCV PoseTrack challenge... Nice!
