### ISSUE TITLE
matlab -nodisplay -nosplash

### ISSUE THREAD

**Issue by NIEYALI** [eldar/pose-tensorflow#3]
Thanks for your great work, but this command 'matlab -nodisplay -nosplash', I don't  understand so much. for my case, I run ./matlab app directly. so how to get the crop files? Thank you very much.

**Comment by eldar** [comment]
Hey, you can also use just matlab command, options `-nodisplay -nosplash` are there to only not lunch the Matlab's graphical user's interface.
