### ISSUE TITLE
Error in "preprocess_single"

### ISSUE THREAD

**Issue by mhsung** [eldar/pose-tensorflow#4]
Hi,

I got the following error message when running "preprocess_single":

.................................................................................................... 13900/15247
.................................................................................................... 14000/15247
.................................................................................................... 14100/15247
.................................................................................................... 14200/15247
.................................................................................................... 14300/15247
.................................................................................................... 14400/15247
.................................................................................................... 14500/15247
.................................................................................................... 14600/15247
.................................................................................................... 14700/15247
.................................................................................................... 14800/15247
.................................................................................................... 14900/15247
.................................................................................................... 15000/15247
.................................................................................................... 15100/15247
.................................................................................................... 15200/15247
...............................................
done
crop_data()
bTrain: 1
refHeight: 400
deltaCrop: 65
bSingle: 0
bCropIsolated: 0
bMulti: 0
bObjposOffset: 1
.................................................................................................... 100/3586
.................................................................................................... 200/3586
.................................................................................................... 300/3586
.................................................................................................... 400/3586
.................................................................................................... 500/3586
.................................................................................................... 600/3586
.................................................................................................... 700/3586
.................................................................................................... 800/3586
.................................................................................................... 900/3586
.................................................................................................... 1000/3586
.................................................................................................... 1100/3586
.................................................................................................... 1200/3586
.................................................................................................... 1300/3586
.................................................................................................... 1400/3586
.................................................................................................... 1500/3586
.................................................................................................... 1600/3586
.................................................................................................... 1700/3586
.................................................................................................... 1800/3586
.................................................................................................... 1900/3586
.................................................................................................... 2000/3586
.................................................................................................... 2100/3586
.................................................................................................... 2200/3586
.................................................................................................... 2300/3586
.................................................................................................... 2400/3586
.................................................................................................... 2500/3586
.................................................................................................... 2600/3586
.................................................................................................... 2700/3586
.................................................................................................... 2800/3586
.................................................................................................... 2900/3586
.................................................................................................... 3000/3586
.................................................................................................... 3100/3586
.................................................................................................... 3200/3586
.................................................................................................... 3300/3586
.................................................................................................... 3400/3586
.................................................................................................... 3500/3586
......................................................................................
done
Error using util_crop_data_train (line 162)
Assertion failed.

Error in crop_data (line 84)
        annolist = func_crop_data_train(p, annolistSubset, imgidxs_sub, rectidxs(imgidxs_sub));

Error in preprocess_single (line 41)
annolist2 = crop_data(p);

The line 162 in 'util_crop_data_train' is the following:
assert(numImgs == length(annolist2));

Could someone please help me to figure out why this happens?
Can I simply ignore this assert?

**Comment by eldar** [comment]
Hey,

Is it still a problem (sorry for the late reply). This piece of code is really just a sanity check if all images
went into training, which in your case seems they have. I tested this code on the MPII dataset from the website, it was working. But I reckon you can ignore the assert.

Cheers,
Eldar.

**Comment by djangogo** [comment]
Hi @eldar 
I encountered the same problem, I noticed that
`
imgidxs1 = find(cellfun(@isempty,rectidxs) == 0);
imgidxs2 = find(DATASET.img_train == bTrain);
imgidxs = intersect(imgidxs1,imgidxs2);
`

these codes do not filter out some pictures which have heads coordinates but do not have joints coordinates.

so in util_crop_data_train

`
.....
ncrops = 1;% here
if (~isempty(setdiff(ridx,rectidxs{imgidx}))) %here
    continue;
end
numImgs = numImgs + 1;%here
if ~isfield(rect(ridx), 'annopoints') || isempty(rect(ridx).annopoints)% here
    continue;
end
.....
.....
.....
if (isempty(annolist2))
    annolist2.image.name = fname;
    annolist2.imgnum = 1;
    annolist2.annorect = rect(ridx);
    annolist2.image_size = image_size;
else
    ncrops = ncrops + 1;% here
    annolist2(ncrops).image.name = fname;
    annolist2(ncrops).imgnum = ncrops;
    annolist2(ncrops).annorect = rect(ridx);
    annolist2(ncrops).image_size = image_size;
end
`
assert(numImgs == length(annolist2));
will failed.

The solutions are
(1) we can comment assert statement

or

(2) we can place
`numImgs = numImgs + 1;`
after
`
if ~isfield(rect(ridx), 'annopoints') || isempty(rect(ridx).annopoints)% here
    continue;
end
`
Cheers,
Feng

**Comment by AlexEMG** [comment]
Dear Feng and Eldar,

I ran into the same problem and just commenting the assert statement allowed the generation of the *.mat file. Thanks!

Alex

**Comment by eldar** [comment]
Hi everyone,

@djangogo Thanks for narrowing it down! I commented out this part for now. If I recall correctly it ran for me without failing the assertion. I will rerun that part.

Cheers,
Eldar.

**Comment by eldar** [comment]
There doesn't seem to be any problems with this issue anymore.
