### ISSUE TITLE
DataLoss problem with the singleperson demo

### ISSUE THREAD

**Issue by Mourula** [eldar/pose-tensorflow#42]
After installing Tensorflow 1.3 and the mandatory Python packages, and downloading the pre-trained model files, I tried to run the **singleperson.py** demo. I got some error messages that I don't understand and I couldn't find any solution or similar problem from the web. _Could someone help me to identify this problem?_
I have Python 3.6 and Ubuntu 16.04.3 LTS. I also tried Tensorflow 1.2. _Does it matter which version to use?_

The problem happens inside the:
> sess, inputs, outputs = predict.setup_pose_prediction(cfg)
```
DataLossError (see above for traceback): not an sstable (bad magic number) 
[[Node: save/RestoreV2_523 = RestoreV2[dtypes=[DT_FLOAT],  _device="/job:localhost/replica:0/task:0/cpu:0"]
(_arg_save/Const_0_0, save/RestoreV2_523/tensor_names, save/RestoreV2_523/shape_and_slices)]]
```

Also, does the warning below have some effect and how should I correct it?
```
WARNING:tensorflow:From /PATH/TO/pose-tensorflow/nnet/pose_net.py:54:
calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training
is deprecated and will be removed after 2017-08-01.
Instructions for updating: Pass is_training directly to the network instead of the arg_scope.
```

Is this related to the #17 - I can't get the demo to work at all.

**Comment by codedreality** [comment]
Check your models, in my case they are html documents with the new download location.
Use the changes from the commit and run `./download_models.sh`, everything should work.

**Comment by Mourula** [comment]
Thank you! That truly solved the problem.
