### ISSUE TITLE
No module config

### ISSUE THREAD

**Issue by dominikheinz** [eldar/pose-tensorflow#47]
Hello.

I installed tensorflow and all requirements.
I installed pose-tensorflow and followed all steps precicly.
I also downlaoded the models with the download_models.py scripts usccessfully.
However, when I want to run singleperson.py :

`TF_CUDNN_USE_AUTOTUNE=0 python3 demo/singleperson.py`

I get the following error:

https://imgur.com/a/G5BzY

How can I fix it?
It looks like the config.py is using python2.7 syntax and changing it to python3 syntax just resulted in mor errors..
What can I do?

**Comment by Mourula** [comment]
Did you run the code inside the demo folder or inside the pose-tensorflow as in the instructions?
Also check the pull request to download the right models... now the code downloads them as wrong file type.

**Comment by Bigwode** [comment]
I had the same problem, How do you handle it ???

**Comment by 3073** [comment]
It is not working. ModuleNotFoundError: No module named 'config'

**Comment by eldar** [comment]
Fixed in 0972020cc811774d0870ea3b49073b034bdee78d.
