### ISSUE TITLE
ValueError: scale cannot be an integer: False

### ISSUE THREAD

**Issue by abozanona** [eldar/pose-tensorflow#49]
When I try to run the `singleperson.py` script, I get the error `ValueError: scale cannot be an integer: False`

![image](https://user-images.githubusercontent.com/12738028/32431304-acc2973a-c2db-11e7-841a-2b40f984defe.png)

**Comment by andreas-eberle** [comment]
I also get this error since I upgraded to the new tensorflow 1.4.

**Comment by eldar** [comment]
Is this still an issue after a fix by @andreas-eberle?

**Comment by abozanona** [comment]
Thanks a lot @andreas-eberle and @eldar .
The code now works like a charm!
