### ISSUE TITLE
Pretrained join detector model

### ISSUE THREAD

**Issue by ParthaEth** [eldar/pose-tensorflow#5]
Hi,

First of all congratulation for you nice work. I am a master's student at ETH trying to replicate the results reported. while trying to download a pretrained weight file I found some standard ResNet models from tensorflow but could not find your final model. I am particularly interested in a pretrained body part detector to use with keras, so 

http://datasets.d2.mpi-inf.mpg.de/deepercut-models/ResNet-152.caffemodel 

did not quite serve the purpose. Have I just failed to locate the link that you've provided already or I have to train from a pretraind std ResNet. 

Would it be possible to share a model compatable with Keras / TensorFlow?

**Comment by eldar** [comment]
Hi, there are pretrained models, check the instructions https://github.com/eldar/pose-tensorflow#demo-code . In particular there is a script to download the models: models/mpii/download_models.sh Closing this one.
