### ISSUE TITLE
image resolution has huge infulence on results

### ISSUE THREAD

**Issue by Clara85** [eldar/pose-tensorflow#6]
Hi, Thanks so much for this great application. It works perfectly when the test image has a resolution that is similar to the test image, however, it fails with both higher and lower resolution images. Did you notice this? Are there any solutions?
Also, how can I test with multiperson using this program?
I use python 3.5, tensorflow 1.0 and windows 10. 
Thanks a lot!
Cheng

**Comment by eldar** [comment]
Hey,

Yeah, unfortunately most of current pose estimation systems work on a limited scale range, and there is an optimal scale that it works best on. Ideally, you have to know scale in advance and pre-scale your image accordingly. I plan to release multi-person version soon, and it should be more robust wrt the scale, but still, there will be an optimal scale at which the system operates.

**Comment by Clara85** [comment]
Thanks for your kind response. In one of your papers you mentioned this article, Spatial Pyramid Pooling in Deep Convolutional Networks for Visual Recognition, do you still think this is the best method for scaling? And please let me know if there's anything I can help for multi-pose estimation.

**Comment by eldar** [comment]
@Clara85 I'm working on porting the multiperson code I have to Tensorflow, it should hopefully be ready by the end of this week.

As for the scale issue: a regular person detector should help, but if for example your input image is of very high resolution, the CNN that is trained for low resolution won't work well. I personally haven't seen SPP nets applied to human pose estimation.
