### ISSUE TITLE
Training on own dataset

### ISSUE THREAD

**Issue by benhunt12** [eldar/pose-tensorflow#63]
I have created a dataset of just a few images(to start) and created the dataset.mat file. 

I have changed the .yaml file in /models/mpii/train to look like...

`dataset: /Users/ben/Desktop/anno/dataset.mat
#dataset_type: "mpii"

pos_dist_thresh: 17
global_scale: 0.8452830189
scale_jitter_lo: 0.85
scale_jitter_up: 1.15

num_joints: 18
#all_joints: true ???

net_type: resnet_101
init_weights: /models/pretrained/resnet_v1_101.ckpt

location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801

intermediate_supervision: true
intermediate_supervision_layer: 12

max_input_size: 850
multi_step:
- [0.005, 10000]
- [0.02, 430000]
- [0.002, 730000]
- [0.001, 1030000]
display_iters: 20
save_iters: 60000

mirror: true`

I've added the path to the dataset.mat file, and commented out the 'dataset: mpii'.

The first time I ran train.py(from the home directory), I got an error saying 'num_joints' doesn't exist. So I went back the the .yaml and added it. It got past that error, but now I'm getting...

`AttributeError: 'EasyDict' object has no attribute 'all_joints'`

I'm not sure what to set all_joints to. Thanks.

**Comment by benhunt12** [comment]
Oh man, I should have read through the example .yaml more closely. Quickly found my error. Sorry!

**Comment by bpeck81** [comment]
Hey Ben, When you trained with your own data did you freeze layers? How long did it take? I am trying to train with specific positions and in dim lighting and want to more tune the network than retrain.
