### ISSUE TITLE
Error during training on COCO dataset

### ISSUE THREAD

**Issue by Naykira** [eldar/pose-tensorflow#65]
Hello! I get a strange error when trying to train a model with the Coco dataset. 
ModuleNotFoundError: No module named 'pycocotools._mask'.
All the instructions are followed as mentioned in the 'Readme'. Any idea as to what might be the cause of it?
Thanks!

**Comment by swg209** [comment]
@eldar @Naykira  Hi, I meet the same problem, did you solve the problem? Hope for your reply. Thx.
