### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by Sugarbank** [eldar/pose-tensorflow#7]
is CPU mode available?

**Comment by Clara85** [comment]
Yes, it works with my surface pro 4, with tensorflow 1.0 cpu, python 3.5 and windows 10

**Comment by SRG2596** [comment]
@Clara85 Hey, please can you give instructions on how to run it? It would be very helpful. Thanks

**Comment by eldar** [comment]
@SRG2596 Hi, I just tested it with Tensorflow 1.2 CPU version on Debian. It works fine, you do not need any specific instructions. Can you be more specific about what doesn't work for you?

**Comment by SRG2596** [comment]
Hello
I was trying to run it on Windows and it showed a lot of errors. Realised
that I didn't download the data set. I'll do that next. If you don't mind,
is it okay if I email you if I have any issues with it.
Thanks a lot for the reply.
- Shreya

**Comment by eldar** [comment]
Hey,

Yes, you have to download the models too. I don't use Windows and download script is Unix only. If one makes a download script that runs on Windows that will be even better.
I'll close this if there's no issues with CPU implementation, you can email if you have any questions.

Cheers,
Eldar.

**Comment by Clara85** [comment]
Hi, sorry I'm late. I ran the single person task on windows 10, python 3.5(this is required by tensorflow), but I haven't tested the new multi person version. I will try it today and let you know.

**Comment by eldar** [comment]
Hi, so the thing is that multi-person code uses some C++ code interfaced through python. The code itself should be cross-platform, but the building instructions are Linux-specific. You will need to compile the code using Cython. Have a look a the script `compile.sh` that does it on Linux.

**Comment by Observerspy** [comment]
@Clara85 hi, did you solve the problem on win for compile.sh?

**Comment by Clara85** [comment]
@Observerspy hi, not yet, cause I used tensorflow gpu without a gpu for another applcation, so I have other problems to solve. I will try it soon. Plz let me know if you make any progress.
