### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rwsarmstrong** [eldar/pose-tensorflow#8]
Hi there,
I'm hoping to do some performance capture in the near future by combining this with multiple vantage points. I was wondering what the license is over the use of this code?  I can't seem to find it anywhere explicitly.  

Either way, thanks so much for posting this.  Amazing stuff.

**Comment by eldar** [comment]
Hi!

Thanks for your interest in our work. I just added the license to the repo (LGPL v3).
If you have any specific question about licensing, please pm.

Cheers,
Eldar.
