### ISSUE TITLE
ImportError: cannot import name 'load_config'

### ISSUE THREAD

**Issue by MSNarry** [eldar/pose-tensorflow#92]
I am having problems running the demo for both single and multiple person, and in both cases I have the error: ImportError: cannot import name 'load_config'. I have instaled the config library as pip install config. I do not know if this could be the problem

**Comment by eldar** [comment]
I think there is an unfortunate clash between names between the `config` package you installed and the `config` module in this repository. I pushed a change that moves config module to the util package, so please pull from the master branch. This should fix your issue.
