### ISSUE TITLE
download_models.sh: curl: not found

### ISSUE THREAD

**Issue by harrisonford** [eldar/pose-tensorflow#94]
Hi, I tried using the sh script to download mpii-single-resenet-101 from a new computer and the download url seems to be unavailable right now, is anybody having the same problem?

**Comment by Arbi112** [comment]
i have the same issue. i remember it worked fine a year ago :P

**Comment by Arbi112** [comment]
Try installing curl by: 
sudo apt-get install curl

**Comment by eldar** [comment]
I added a fix to the download scripts, that will make them use `wget` when `curl` is not available.
