### ISSUE TITLE
The type of annotation file for train model

### ISSUE THREAD

**Issue by jingshaoli** [eldar/pose-tensorflow#99]
Hi,eldar.
Thanks for your great work
I want to train the model with my own dataset. I used the annotation tool(https://github.com/visipedia/annotation_tools) to mark the joint and finally get a json type file. Do I need to convert it to matlab type? I noticed that the annotation file that I downloaded from coco's official website is also  json type. Do I need to convert the annotation file to matlab type file when training with coco dataset?

**Comment by MMathisLab** [comment]
If you want, we made a wrapper for this code (plus some other extensions), so you can load your own data. see more here: https://github.com/AlexEMG/DeepLabCut
